[package]
name = "shapir"
version = "0.1.0"
authors = ["workanator <workanator@gmail.com>"]
description = "Unofficial ShareFile REST API SDK"
keywords = ["ShareFile", "SDK", "REST"]
license = "MIT"
repository = "https://github.com/workanator/shapir"
documentation = "http://shapir.wellknownteam.ru"

[dependencies]
serde_json = "0.7"
hyper = "0.9"
url = "1.0"
chrono = "0.2"
md5 = "0.1"
rustc-serialize = "0.3"
