[package]
name = "shapir"
version = "0.0.2"
authors = ["workanator <workanator@gmail.com>"]
description = "Unofficial ShareFile REST API SDK"
keywords = ["ShareFile", "SDK", "REST"]
license = "MIT"
repository = "https://github.com/workanator/shapir"
documentation = "http://shapir.wellknownteam.ru"

[dependencies]
serde_json = "0.7"
hyper = "0.8"
url = "0.5"
chrono = "0.2"
